apiVersion: apps/v1
kind: Deployment

metadata:
  name: cicd-demo

spec:
  replicas: 25

  selector:
    matchLabels:
      app: cicd-demo

  template:
    metadata:
      labels:
        app: cicd-demo

    spec:
      containers:
      - name: cicd-demo
        image: manideept27/cicd-demo:v3.4.3

        ports:
        - containerPort: 80